#!/bin/sh
#
# A command line tool for solr.
#
# author: tbl
#

set -e

if [ -a lib/classes ]
    then
       find -L lib/classes -name *.java | xargs javac -classpath $SOLR_CMD_UTILS_HOME/lib/*.jar
fi

if [ -a $SOLR_CMD_UTILS_HOME/lib/classes ]
    then
       find -L $SOLR_CMD_UTILS_HOME/lib/classes -name *.java | xargs javac -classpath $SOLR_CMD_UTILS_HOME/lib/*.jar
fi