#!/bin/sh
#
# A command line tool for solr.
#
# author: tbl
#

set -e

if [ -d lib/classes ]
    then
       find -L lib/classes -name *.java | xargs javac -classpath "$SOLR_CMD_UTILS_HOME/lib/*"
fi

if [ -d $SOLR_CMD_UTILS_HOME/lib/classes ]
    then
       find -L $SOLR_CMD_UTILS_HOME/lib/classes -name *.java | xargs javac -classpath "$SOLR_CMD_UTILS_HOME/lib/*"
fi
